//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerXP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TallerEntity : DbContext
    {
        public TallerEntity()
            : base("name=TallerEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arreglo> Arreglos { get; set; }
        public DbSet<Auto> Autos { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<LineaArreglo> LineaArreglos { get; set; }
    }
}
